name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    if: ${{ github.event_name != 'pull_request' || !startsWith(github.head_ref, 'release-please--branches--') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup proto toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Install dependencies
        run: proto run yarn -- install --immutable

      - name: Lint
        run: proto run yarn -- lint

      - name: Test
        run: proto run yarn -- test

  verify-ffmpeg-runtime:
    if: ${{ github.event_name != 'pull_request' || !startsWith(github.head_ref, 'release-please--branches--') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup proto toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Install dependencies
        run: proto run yarn -- install --immutable

      - name: Verify ffmpeg runtime
        run: proto run yarn -- verify:ffmpeg
